name: Release

on:
  create:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build for Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o bin/linux/amd64/tc-redirect-tap-linux-amd64

      - name: Build for Linux arm64
        run: GOOS=linux GOARCH=arm64 go build -o bin/linux/arm64/tc-redirect-tap-linux-arm64

      - name: Build for Darwin amd64
        run: GOOS=darwin GOARCH=amd64 go build -o bin/darwin/amd64/tc-redirect-tap-darwin-amd64

      - name: Build for Darwin arm64
        run: GOOS=darwin GOARCH=arm64 go build -o bin/darwin/arm64/tc-redirect-tap-darwin-arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/linux/amd64/tc-redirect-tap-linux-amd64
            bin/linux/arm64/tc-redirect-tap-linux-arm64
            bin/darwin/amd64/tc-redirect-tap-darwin-amd64
            bin/darwin/arm64/tc-redirect-tap-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}